{
  "current": 1405,
  "total": 7207,
  "status": "processing",
  "processed_companies": 1,
  "analyzed_companies": 65,
  "current_company": "Clowder",
  "company_progress": [
    {
      "name": "RIOS Intelligent Machines",
      "status": "completed",
      "score": 0,
      "start_time": 1746254228.216292,
      "analysis_time": 1.0,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "Darklang",
      "status": "completed",
      "score": 0,
      "start_time": 1746254228.217161,
      "analysis_time": 1.0,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "Oort ",
      "status": "completed",
      "score": 0,
      "start_time": 1746254228.228432,
      "analysis_time": 1.1,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "Sway",
      "status": "completed",
      "score": 0,
      "start_time": 1746254228.229339,
      "analysis_time": 1.0,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "Galileo Financial Technologies",
      "status": "error",
      "score": 0,
      "start_time": 1746254228.241373,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2256' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Loyal",
      "status": "error",
      "score": 0,
      "start_time": 1746254228.241409,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2257' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "HelloSign",
      "status": "error",
      "score": 0,
      "start_time": 1746254228.24142,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2258' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Veeam Kasten",
      "status": "error",
      "score": 0,
      "start_time": 1746254228.241932,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2251' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Flume Health",
      "status": "error",
      "score": 0,
      "start_time": 1746254228.241951,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2252' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Stanza",
      "status": "error",
      "score": 0,
      "start_time": 1746254228.241959,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2253' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Uniform",
      "status": "completed",
      "score": 0,
      "start_time": 1746254228.589461,
      "analysis_time": 1.2,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "Gutsy",
      "status": "error",
      "score": 0,
      "start_time": 1746254228.758177,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2264' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Guoxinex",
      "status": "error",
      "score": 0,
      "start_time": 1746254228.758227,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2265' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Gig and Take",
      "status": "error",
      "score": 0,
      "start_time": 1746254228.758236,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2266' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Cypherpath Inc.",
      "status": "error",
      "score": 0,
      "start_time": 1746254228.758243,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2267' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Arist",
      "status": "completed",
      "score": 0,
      "start_time": 1746254229.254634,
      "analysis_time": 0.9,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "Nest Genomics ",
      "status": "completed",
      "score": 0,
      "start_time": 1746254229.261186,
      "analysis_time": 1.7,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "Pilot Project Brewing",
      "status": "completed",
      "score": 0,
      "start_time": 1746254229.268165,
      "analysis_time": 1.0,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "Say",
      "status": "error",
      "score": 0,
      "start_time": 1746254229.274403,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2282' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Aspen RxHealth",
      "status": "error",
      "score": 0,
      "start_time": 1746254229.274431,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2283' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Fletch",
      "status": "completed",
      "score": 0,
      "start_time": 1746254229.320397,
      "analysis_time": 0.9,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "SimpliContract",
      "status": "error",
      "score": 0,
      "start_time": 1746254229.328667,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2288' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "8Flow",
      "status": "error",
      "score": 0,
      "start_time": 1746254229.328698,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2289' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Aniline",
      "status": "error",
      "score": 0,
      "start_time": 1746254229.328706,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2290' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Variant Bio",
      "status": "error",
      "score": 0,
      "start_time": 1746254229.328713,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2291' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Soliyarn",
      "status": "completed",
      "score": 0,
      "start_time": 1746254229.837623,
      "analysis_time": 1.6,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "Black Crow AI",
      "status": "error",
      "score": 0,
      "start_time": 1746254229.844791,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2294' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Sonex Health",
      "status": "error",
      "score": 0,
      "start_time": 1746254229.844819,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2295' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "7thOnline",
      "status": "error",
      "score": 0,
      "start_time": 1746254229.844827,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2296' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "VIOLET",
      "status": "error",
      "score": 0,
      "start_time": 1746254229.844833,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2297' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "LANGaware",
      "status": "completed",
      "score": 0,
      "start_time": 1746254230.263395,
      "analysis_time": 1.0,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "Althea, CMO",
      "status": "completed",
      "score": 0,
      "start_time": 1746254230.271786,
      "analysis_time": 1.0,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "BRIVAS PRIME",
      "status": "error",
      "score": 0,
      "start_time": 1746254230.278968,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2301' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Craft Standard Draft Cocktails",
      "status": "error",
      "score": 0,
      "start_time": 1746254230.278996,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2302' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Metadome.ai",
      "status": "error",
      "score": 0,
      "start_time": 1746254230.279004,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2303' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Depix AI",
      "status": "completed",
      "score": 0,
      "start_time": 1746254230.934948,
      "analysis_time": 0.9,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "Causality Link",
      "status": "completed",
      "score": 0,
      "start_time": 1746254230.941653,
      "analysis_time": 1.0,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "Cubeyou",
      "status": "error",
      "score": 0,
      "start_time": 1746254230.948801,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2308' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "AgencyQ",
      "status": "error",
      "score": 0,
      "start_time": 1746254230.948828,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2309' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Kepler Communications Inc.",
      "status": "error",
      "score": 0,
      "start_time": 1746254230.948836,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2310' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Momentum.io",
      "status": "completed",
      "score": 0,
      "start_time": 1746254231.31522,
      "analysis_time": 1.2,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "InDevR, Inc.",
      "status": "completed",
      "score": 0,
      "start_time": 1746254231.324613,
      "analysis_time": 0.9,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "Flashfood",
      "status": "error",
      "score": 0,
      "start_time": 1746254231.334748,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2315' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Saltbox",
      "status": "error",
      "score": 0,
      "start_time": 1746254231.334779,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2316' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Cheetah Digital",
      "status": "error",
      "score": 0,
      "start_time": 1746254231.334789,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2317' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Syncly ",
      "status": "completed",
      "score": 0,
      "start_time": 1746254231.39286,
      "analysis_time": 0.9,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "Hummingbirds",
      "status": "error",
      "score": 0,
      "start_time": 1746254231.401266,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2321' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Prism Skylabs",
      "status": "error",
      "score": 0,
      "start_time": 1746254231.401301,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2322' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Webs",
      "status": "error",
      "score": 0,
      "start_time": 1746254231.40131,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2323' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Pod Foods",
      "status": "error",
      "score": 0,
      "start_time": 1746254231.401316,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2324' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Yugabyte",
      "status": "completed",
      "score": 0,
      "start_time": 1746254231.947374,
      "analysis_time": 1.2,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "Cultivate",
      "status": "completed",
      "score": 0,
      "start_time": 1746254231.954803,
      "analysis_time": 0.7,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "MarketReader",
      "status": "error",
      "score": 0,
      "start_time": 1746254231.961495,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2328' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Cascade AI",
      "status": "error",
      "score": 0,
      "start_time": 1746254231.961521,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2329' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Zulu Pods, Inc.",
      "status": "error",
      "score": 0,
      "start_time": 1746254231.961529,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2330' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Goloot",
      "status": "completed",
      "score": 0,
      "start_time": 1746254232.300386,
      "analysis_time": 0.8,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "CaaMTech",
      "status": "analyzing",
      "score": 0,
      "start_time": 1746254232.307158,
      "analysis_time": 0,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "AOBiome Therapeutics, Inc.",
      "status": "error",
      "score": 0,
      "start_time": 1746254232.315492,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2335' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Anyword",
      "status": "error",
      "score": 0,
      "start_time": 1746254232.315525,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2336' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "SmashFly Technologies",
      "status": "error",
      "score": 0,
      "start_time": 1746254232.315533,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2337' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Critical Data Solutions",
      "status": "analyzing",
      "score": 0,
      "start_time": 1746254232.569991,
      "analysis_time": 0,
      "retry_count": 0,
      "error_message": null
    },
    {
      "name": "ASKGENE PHARMA, INC.",
      "status": "error",
      "score": 0,
      "start_time": 1746254232.577245,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2341' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Sleuth",
      "status": "error",
      "score": 0,
      "start_time": 1746254232.577275,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2342' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Safesite",
      "status": "error",
      "score": 0,
      "start_time": 1746254232.577283,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2343' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    },
    {
      "name": "Clowder",
      "status": "error",
      "score": 0,
      "start_time": 1746254232.577289,
      "analysis_time": 0.0,
      "retry_count": 0,
      "error_message": "Task <Task pending name='Task-2344' coro=<analyze_company_async() running at /Users/ericzhu/Documents/GitHub/lead-list-generator/app.py:169>> got Future <Future pending> attached to a different loop"
    }
  ],
  "start_time": 1746254228.214667,
  "should_stop": false
}